export default {
    verifyIdentity: {
        changeIdMenu: {
            title: '身分証の提出',
        },
        confirmButton: 'この写真に変更',
        newUploadButton: '新しくアップロード',
        pickAgainButton: '撮り直す',
        driverCard: '運転免許証',
        healthCard: '健康保険証',
        passportCard: 'パスポート',
        individualNumberCard: '個人番号カード',
        residentRegisterCard: '住民基本台帳カード（顔写真付き）',
        title: '身分証を撮影',
        titleDriver: '身分証の撮影',
        driverCardSubTitle: '表裏の写真をアプロードしてください。',
        healthCardSubTitle: '表裏の写真をアプロードしてください。',
        individualNumberCardSubTitle: '写真をアプロードしてください。',
        residentRegisterCardSubTitle: '写真をアプロードしてください。',
        passportCardTitle: '写真をアプロードしてください。',
        changeIdSubTitle: '本人確認のため身分証の提出が必要です。提出する身分証を選択してください。',
        currentIdSubTitle: '現在登録中の身分証',
        confirmTitle: 'この写真でよろしかったですか？',
        takePhotoPlaceholder: '表面の写真を撮影',
        noteTitle: '注意事項',
        modal: {
            changedId: '身分証を変更しました',
        },
        driver: {
            note1: '有効期限内であること',
            note2: '住所変更の記載が裏面にある場合は、公印が確認できるもの',
            buttonConfirm: '次へ',
        },
        health: {
            buttonConfirm: '次へ',
            note: '記載されている保険者番号をテープやふせん等で隠した状態でご提出ください。',
        },
        individualNumber: {
            note1: '有効期限内であること',
            note2: '顔写真入りのページと所持人記入欄をアップロードしてください',
            buttonConfirm: '次へ',
        },
        passport: {
            note1: '有効期限内であること',
            note2: '顔写真入りのページと所持人記入欄をアップロードしてください',
            buttonConfirm: '次へ',
        },
        residentRegister: {
            note1: '有効期限内であること',
            note2: '顔写真入りのページと所持人記入欄をアップロードしてください',
            buttonConfirm: '次へ',
        },
    },
    actionSheet: {
        photo: 'Choose from Photos',
        camera: 'Take from Camera',
        cancel: 'Cancel',
    },
    button: {
        done: '完了',
    },
    noticeSetting: {
        title: '通知設定',
        notice: 'お知らせ',
        shipNotification: '発送関連の通知',
        noteText: '※必ず現住所が記載されているものをご提出してください',
    },
    transactionHistoryDetail: {
        title: '取引履歴詳細',
        modalTitle: '追跡番号を入力してください',
        errorParcel: '追跡番号が正しくありません',
        dateTime: '取引日時',
        time: '所要時間：{{mins}}分{{seconds}}靴',
        timeMinute: '所要時間：{{timeReview}}分',
        info: '査定品情報',
        category: 'カテゴリー：{{name}}',
        brand: 'ブランド：{{name}}',
        code: 'シリアルナンバー：{{name}}',
        price: '売却金額',
        money: '{{money}}円',
        inCharge: '担当',
        tab1: {
            pleaseShip: '発送を行ってください',
            packAndShip: '査定品を梱包し発送してください。',
            packingMethod: '梱包方法はこちら',
            button: '発送を通知する',
        },
        tab2: {
            sendText: '発送済み',
            packAndShip: '査定品を梱包し発送してください。',
            button: 'レビューを書',
            goToReview: 'レビューを書く',
            changeParcel: '追跡番号を編集',
            parcel: '追跡番号: {{code}}',
        },
        tab3: {
            assessmentText: '査定のみ',
            thankYou: 'またのご利用お待ちしています。',
        },
        textModalParcel: '追跡番号を変更しました',
    },
    history: {
        empty: {
            button: 'さっそく査定する',
            title: '査定・取引履歴がありません',
            subTitle: 'まずはお持ちの品物を査定してみましょう。',
            listNotify: '査定のみのお品物はありません',
        },
        codePlaceholder: '0000-0000-0000',
        title: '取引履歴',
        pendingShipList: '未発送',
        sentList: '発送済み',
        notSellList: '査定のみ',
        category: 'カテゴリー',
        brand: 'ブランド',
        price: '{{price}}円',
        packingGuideButtonText: '梱包のガイドはこちら',
        notifyShipButtonText: '発送を通知する',
        assessmentButtonText: 'この査定内容で取引する',
    },
    common: {
        defaultLanguage: 'English',
        close: '閉じる',
        noText: 'テキストなし',
        noData: 'データなし',
        cancel: 'キャンセル',
        confirm: '決定',
        no: 'いいえ',
        yes: 'はい',
        justNow: 'さっき',
        prevDay: '日前',
        confirmAction: 'この内容で査定する',
        resendOtp: '電話番号に認証コードを送信しました。\nご確認ください。',
        invalidInput: '口座名義を正しく入力してください。',
        next: '次へ',
        noHave: 'なし',
        closeTransaction: '査定員が取引を終了しました。',
        confirmActionPrecious: 'この内容で査定開始',
        adminCloseTransaction: '査定員が取引を終了しました。',
        adminCompleteTransaction: '査定員が査定を終了しました。',
        timeOutPrepare: '只今大変混み合っております。\n暫くしてから、もう一度試してください。',
        reviewPending: 'ストアに上がった後、レビューを頂きます。',
    },
    modalInput: {
        title: 'hello',
        close: 'Close',
        button: 'displayModal1',
    },
    tab: {
        home: 'ホーム',
        assessment: '査定',
        notice: 'お知らせ',
        history: '取引履歴',
        account: 'アカウント',
    },
    alert: {
        button: {
            no: 'いいえ',
            yes: 'はい',
        },
    },
    noData: {
        noDataList: 'データはありません',
        noDataRateList: '評価がまだありません',
        noDataHoliday: 'なし',
    },
    login: {
        placeholderEmail: 'メールアドレス',
        placeholderPassword: 'パスワード',
        buttonLogin: 'ログイン',
        rememberText: 'ログイン状態を保持',
        forgotPasswordText: 'パスワードを忘れた方はこちら',
        registerText: '新規会員登録はこちら',
    },
    register: {
        emailPlaceholder: 'sample@demo.webcom',
        password: 'パスワード',
        passwordPlaceholder: 'パスワード',
    },
    registerAccount: {
        password: 'パスワード',
        passwordConfirm: 'パスワード（再入力）',
        backButton: '前の画面',
        title: '新規会員登録はこちら',
        passwordPlaceholder: 'パスワード',
    },
    validateMessage: {
        signIn: '入力されたイメルまたはパスワードが正しくありません。',
        infoInvalid: 'Info invalid',
        notCompleted: '全ての項目に入力してください',
        emailNotRegister: '入力したメールアドレスがまだ登録されていません',
        validatePassword: 'パスワードは半角英数字で6文字以上入力する必要があります',
        emailInvalid: 'メールアドレスの形式が間違っています。',
        passwordLength: 'At least 6 character of password',
        confirmPasswordLength: 'At least 6 character of confirm password',
        passwordNotMatch: '入力された新パスワードが一致しません。ご確認ください。',
        emailEmpty: '全ての項目を入力してください。',
        messageLength: '1文字以上 255文字以内',
    },
    sendOTPMessage: {
        success: '新規コードを送りました。',
        invalidOTP: '認証コードは正しくありません。',
    },
    sendOTP: {
        title: '認証コード',
        titleForgotPassword: 'パスワードを忘れた',
        sendForgotPassword: '確認',
        backButton: '前の画面',
        descriptionNext:
            '入力したメールアドレスに通知メールを送信しました。\n 認証コードを入力し、「次へ」ボタンを押してください。有効期限は24時間です。',
        descriptionConfirm:
            '入力したメールアドレスに通知メールを送信しました。\n 認証コードを入力し、「確認」ボタンを押してください。有効期限は24時間です。',
        description:
            '入力したメールアドレスに通知メールを送信しました。認証コードを入力し、「登録」ボタンを押してください。有効期限は24時間です。',
        resend: '再送信',
        buttonSend: '登録',
        buttonNext: '次へ',
    },
    errorMessage: {
        emailExisted: 'メールアドレスが既に存在します',
    },
    sendEmail: {
        title: 'パスワードを忘れた',
        sendButtonTitle: '次へ',
    },
    picker: {
        pickItem: 'アイテムを選択してください',
    },
    assessment: {
        title: 'カテゴリーを選択',
        shootingProduct: '査定品の撮影',
        textTakePicture: '査定品の写真を撮影してください。',
        wholePhoto: '全体の写真',
        logoPhoto: 'ロゴの写真',
        one: '1',
        two: '2',
        take: '写真を撮影',
        example: 'ロゴの撮影例',
        logoInside: 'ロゴは内側にある場合もあります。',
        check: '査定内容を確認',
        note: '全体が写るように撮影してください',
        reTake: '撮り直す',
        done: '完了',
        titleMethod: '査定方法の選択',
        videoCall: 'ビデオ通話で査定する',
        message: 'チャットで査定する',
        recommend: 'おすすめ',
        start: '査定開始',
        clock: '査定員は現在準備中です',
        noteTime: '10分以内に開始します。\nもう少々お待ちください。',
        time: '5:00',
        textCall: '査定員から着信が来ています',
        confirmCall: '応答して査定開始',
        brandNotExist: '一覧にブランド名がない場合',
        exampleClothing: '洋服のタグ部分を撮影してください',
        exampleShoes: '表面又は中敷きにあるロゴを撮影して下さい。',
        checkHasBrand: '査定内容を確認',
        titleModalEdit: 'カテゴリーを選択',
        clockStop: '只今大変混み合っております',
        noteTimeStop: '申し訳ありません。\nもう少々お待ちください。',
        slide: {
            titleOne: '付属品はありますか？',
            contentOne: '付属品もあわせて査定で査定額が\nアップします。',
            titleTwo: '査定中は顔出しなしOK',
            contentTwo: '査定品のみビデオに写して査定す\nることも可能です。',
        },
        confirm: {
            title: '査定内容の確認',
            category: 'カテゴリー',
            brand: 'ブランド',
            image: '査定品写真',
            confirm: 'この内容で査定する',
            edit: '修正する',
            cancel: '査定をキャンセル',
            titleEdit: '査定内容の修正',
            titleCertificate: '鑑定証の撮影',
            titleCertificateNew: '各種証明書の撮影',
            takeCertificate: '各種証明書の写真を撮影してください。',
            checkCertificate: '査定内容を確認',
            taking: '写真の撮影',
            noteCertificate: '書類が枠内に収まるように撮影してください',
            titleEditCertificate: '査定品の撮影',
            confirmCertificate: 'この内容で査定開始',
            editCertification: '修正する',
            imageCertificate: '鑑定書写真',
            deleteAssessment: '査定をキャンセルします。\nよろしいですか。',
            preview: 'ブランドなしの貴金属・アクセサリーは各種証明書がないと買取できません',
        },
        conversation: {
            title: 'チャットで査定',
            placeHolder: 'メッセージを入力',
            cancelConversation: 'トークから退室します。\nよろしいですか。',
            cancelClose: 'キャンセル',
            confirmClose: '退室する',
        },
    },
    tutorial: {
        title: {
            step1: 'カテゴリーをえらぶ',
            step2: 'ビデオ通話で即査定',
            step3: '査定後に即入金・即現金化',
        },
        subTitle: {
            step1: '査定したい品物の情報を選択し、\n写真を撮影してください。',
            step2: '「通話」ボタンを押すと\n査定員がビデオ通話で査定を開始。',
            step3: '取引成立後、ネット銀行・電子マネー\nご登録で即お振り込み。',
        },
        textList: {
            exit: {
                title: '迅速な対応',
                value: '会員制にすることで”査定した\nい時にすぐ査定”を実現します。',
            },
            payment: {
                title: '高額査定の実現',
                value: '丁寧にコミュ二ケーションを取\nり、納得のいく査定を行います。',
            },
            warning: {
                title: '不正な取引防止の徹底',
                value: '万一トラブル・不正があった際\nは即対応・処理いたします。',
            },
            inviteCode: '招待コードを入力する',
            notHaveInviteCode: '招待を受けていない方',
        },
        appName: 'SELL ME',
        step: 'STEP',
        skip: 'SKIP',
        terms: {
            title: '利用規約に同意してください',
            agree: 'に同意する',
            termsOfService: '利用規約',
            policy: 'プライバシーポリシー',
            btnAgree: '次へ',
            ageTitle: '20歳以上ですか？',
            ageContent: 'SELL MEでは未成年の方との取引ができません。',
            no: 'いいえ',
            yes: 'はい',
        },
        inviteCode: {
            title: '招待コードを入力してください',
            noHaveCode: '招待コードをお持ちでない方はこちら',
            placeholder: '000000',
            error: '招待コードが違います',
        },
    },
    brand: {
        title: 'ブランドを選択',
        search: 'ブランド名を検索',
        noCategory: '該当するブランドがありません。',
        brandNotFound: '一覧にブランド名がない場合はこちら',
    },
    homeView: {
        title: 'SELL ME',
        homeView: {
            title: '直近の査定実績',
        },
        notification: '通知をONにすると\nお得な情報を受け取れます！',
        next: '次へ',
        titleNotification: '“SELL ME”は通知を送信します。\nよろしいですか？',
        messageNotification:
            '通知方法は、テキスト、サウンド、アイコン\nバッジが利用できる可能性があります。\n通知方法はアカウントから設定出来ます。',
        detail: '家にあるブランド品を\nいますぐお金に',
        startAssessment: '査定を開始する',
        help: '初めての方へ  ー利用ガイド',
        category: '査定カテゴリー',
    },
    identify: {
        placeholderPhone: '(123)000-0000',
        title: '本人確認を行います\n電話番号を入力してください',
        titleOtp: 'SMSに送信された認証コードを\n入力してください',
        resendSms: 'SMSを再送',
        next: '次へ',
        notIdentifyPhone: 'この電話番号は認証できません',
        notValidOtp: '認証コードが違います',
    },
    account: {
        personInfo: '個人情報設定',
        notification: '通知設定',
        manual: 'ご利用ガイド',
        help: 'ヘルプ・お問い合わせ',
        policy: 'プライバシーポリシー',
        terms: '利用規約',
    },
    personInfo: {
        title: '個人情報設定',
        changeDestination: '振込先の変更',
        changeAddress: '住所・氏名の変更',
        changeId: '身分証の変更',
        changePhoneNumber: '電話番号の変更',
    },
    changePhone: {
        title: '電話番号の変更',
        currentPhone: '現在の電話番号: {{phone}}',
        placeholder: '新しい電話番号を入力',
        sendSMS: 'SMSを送信する',
        headerOtp: '認証コード',
        btnChange: '電話番号を変更',
        resendSms: 'SMSを再送',
        success: '電話番号を変更しました',
    },
    changeId: {
        subTitle: '現在登録中の身分証',
        newUploadButton: '新しくアップロード',
        menu: {
            healthInsuranceCard: '健康保険証',
            passport: 'パスポート',
            individualCard: '個人番号カード',
            residentRegisterCard: '住民基本台帳カード（顔写真付き）',
            note: '※必ず現住所が記載されているものをご提出してください',
            description: '本人確認のため身分証の提出が必要です。提出\nする身分証を選択してください。',
        },
    },
    videoView: {
        leaveRoom: '退室する',
        cancel: 'キャンセル',
        confirmLeave: 'ビデオ通話から退室します。\nよろしいですか。',
        placeholder: 'メッセージを入力',
        acceptOffer: '取引が完了しました。',
        reject: '拒否する',
        sell: '売却する',
        offer: '{{cost}}円で買取オファーが来ています。',
        offerComing: '買取オファーが来ています',
        brand: 'ブランド：{{brand}}',
        category: 'カテゴリ：{{category}}',
        amount: '金額：',
        futureFlow: '今後の流れ',
        firstTimeShip: '初回のみ集荷員が出向いての発送\nになります',
        pleasePurchase: '集荷が完了次第、買取額を入金',
        note: '次回から取引完了後すぐに入金',
        need: '必要なこと',
        followStep: '以下の手続きをお願いします。',
        enterInfo: '名前、現住所の記入',
        transfer: '振込先口座の登録',
        message: '{{name}}:  ',
        me: 'あなた',
        namePersonReview: '査定員',
        adminMuteVideo: '査定員側がカメラをオフしています。',
    },
    profile: {
        title: '本人情報の入力',
        address: '住所',
        postalCode: '郵便番号',
        autoComplete: '住所自動入力',
        ken: '都道府県',
        hintKen: '選択してください',
        city: '市区町村',
        hintCity: '例）渋谷区広尾',
        addressDetail: '番地・建物名',
        hintAddressDetail: '例）1-5-1 マンション4番館-803',
        fullName: '氏名',
        hintFirstName: '例）山田',
        hintLastName: '例）太郎',
        fullNameFurigana: 'フリガナ',
        hintFirstNameFurigana: '例）ヤマダ',
        hintLastNameFurigana: '例）タロウ',
        next: '次へ',
        errorPostalCode: '郵便番号を入力してください',
        confirmChange: 'この本人情報に変更',
    },
    transfer: {
        select: {
            title: '振込み先の選択・入力',
            bank: '銀行',
            accountType: '口座種別',
            pleaseSelect: '選択してください',
            branchCode: '支店コード',
            hintDigit: '数字{{number}}桁',
            accountNumber: '口座番号',
            accountFullName: '口座名義',
            hintAccountFullName: '全角カナ・英字',
            accountFullNameFurigana: '口座名義(フリガナ)',
            hintAccountFullNameFurigana: '全角カナ',
            note:
                '※口座番号が7桁未満の場合は、先頭に0をつけて7桁にしてください。(例：12345の場合0012345)。8桁以上の場合は最後の「1」\nを外してください。(例：12345671の場合1234567)',
            next: '次へ',
            confirmChangeTransfer: 'この内容で変更',
            successChange: '振込み先を変更しました',
            requireKatakana: 'フリガナを正しく入力してください。',
        },
        accountType: {
            title: '口座種別',
            usually: '普通',
            current: '当座',
            save: '貯蓄',
        },
        confirm: {
            title: 'お支払い内容の確認',
            textConfirm: 'この内容でお支払いします。よろしいですか。',
            destination: 'お支払い先',
            change: '変更',
            examBank: '楽天銀行  普通',
            branchCode: '支店コード : {{branchCode}}',
            accountNumber: '口座番号 : {{accountNumber}}',
            accountName: '口座名義 : {{accountName}}',
            accountNameFurigana: '口座名義(フリガナ) : {{accountName}}',
            address: '住所',
            paymentAmount: 'お支払い額',
            amount: '{{amount}}円',
            completePayment: '支払い手続きを完了する',
        },
        complete: {
            title: '支払い完了',
            textComplete: 'お支払い手続きが完了しました',
            thank: 'ご利用ありがとうございます。',
            remind: '集荷の確認が完了後、支払いを行います。',
            home: 'ホームに戻る',
        },
        bank: {
            title: '銀行の選択',
            placeholderSearch: '銀行名を検索',
        },
    },
    provinceView: {
        title: '居住地の都道府県を選択してく\nださい',
        start: '利用開始',
    },
    featureApp: {
        title: 'SELL MEは紹介型会員制です',
    },
    changeAddress: {
        success: '住所・氏名を変更しました',
        requireKatakana: 'フリガナを正しく入力してください。',
    },
    notification: {
        title: 'お知らせ',
        all: 'システム通知',
        me: 'あなた宛',
    },
    permissions: {
        camera: '査定商品や身分証明書の写真と取るため、{{appName}}がカメラへのアクセスへ求めています。',
        audio: 'ビデオ電話の査定を開始できるため、{{appName}}がマイクロソフトへのアクセスへ求めています。',
        unavailable: {
            camera: 'この端末で写真を撮る機能は無効です。',
            audio: 'この端末で記録機能は無効です。',
        },
        limited: '許可は制限されています：いくつかのアクションが可能です。',
    },
};
