const AUTHENTICATE_ROUTE = {
    LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
    REGISTER: '@AUTHENTICATE_ROUTE/REGISTER',
    FORGOTPASS: '@AUTHENTICATE_ROUTE/FORGOTPASS',
    SEND_OTP: '@AUTHENTICATE_ROUTE/SEND_OTP',
    CHANGEPASS: '@AUTHENTICATE_ROUTE/CHANGEPASS',
    VIDEO: 'VIDEO',
    LIVE_STREAM: 'LIVE_STREAM',
    INTRO: 'INTRO',
};

const APP_ROUTE = {
    MAIN_TAB: 'MAIN_TAB',
};

const HOME_ROUTE = {
    ROOT: 'HOME_ROOT',
    HOME: 'HOME',
    HOME_DETAIL: 'HOME_DETAIL',
    WEB_VIEW: 'WEB_VIEW',
    HOME_DATA: 'HOME_DATA',
    HOME_USER_LIST: 'HOME_USER_LIST',
};

const ACCOUNT_ROUTE = {
    ROOT: 'SETTING_ROOT',
    PERSON_INFO: 'PERSON_INFO',
    CHANGE_PHONE: 'CHANGE_PHONE',
    OTP_CHANGE_PHONE: 'OTP_CHANGE_PHONE',
    ADDRESS: 'ADDRESS',
    SETTINGS_NOTIFICATION: 'SETTINGS_NOTIFICATION',
    CHANGE_ID: 'CHANGE_ID',
    UPLOAD_PASSPORT: 'UPLOAD_PASSPORT',
    UPLOAD_HEALTH_CARD: 'UPLOAD_HEALTH_CARD',
    UPLOAD_DRIVER_CARD: 'UPLOAD_DRIVER_CARD',
    UPLOAD_RESIDENT_REGISTER_CARD: 'UPLOAD_RESIDENT_REGISTER_CARD',
    CHANGE_ID_MENU: 'CHANGE_ID_MENU',
    PICK_IMAGE_ID: 'PICK_IMAGE_ID',
    PICK_AGAIN: 'PICK_AGAIN',
    CONFIRM_CARD: 'CONFIRM_CARD',
};

const NOTIFICATION_ROUTE = {
    ROOT: 'NOTIFICATION_ROOT',
};

const HISTORY_ROUTE = {
    ROOT: 'HISTORY_ROOT',
    DETAIL: 'HISTORY_DETAIL',
};

const ASSESSMENT_ROUTE = {
    ROOT: 'ASSESSMENT_ROUTE',
    BRAND_CATEGORY_VIEW: 'BRAND_BAG_VIEW',
    PRECIOUS_VIEW: 'PRECIOUS_VIEW',
    ASSESSMENT_PRODUCT: 'ASSESSMENT_PRODUCT',
    VIDEO_CALL_VIEW: 'VIDEO_CALL_VIEW',
    METHOD_ASSESSMENT: 'METHOD_ASSESSMENT',
    PREPARE_TIME: 'PREPARE_TIME',
    CONFIRM_CALL: 'CONFIRM_CALL',
    CONFIRM_CONTENT: 'CONFIRM_CONTENT',
    EDIT_CONTENT: 'EDIT_CONTENT',
    TAKE_CERTIFICATE: 'TAKE_CERTIFICATE',
    PRECIOUS_HAS_BRAND: 'PRECIOUS_HAS_BRAND',
    SELECT_TRANSFER: 'SELECT_TRANSFER',
    SELECT_BANK: 'SELECT_BANK',
    SELECT_ACCOUNT_TYPE: 'SELECT_ACCOUNT_TYPE',
    CONFIRM_TRANSFER: 'CONFIRM_TRANSFER',
    COMPLETE_TRANSFER: 'COMPLETE_TRANSFER',
    CONVERSATION: 'CONVERSATION',
    ASSESSMENT_VIEW: 'ASSESSMENT_VIEW',
};

const TAB_NAVIGATION_ROOT = {
    HOME_ROUTE,
    ACCOUNT_ROUTE,
    NOTIFICATION_ROUTE,
    HISTORY_ROUTE,
    ASSESSMENT_ROUTE,
};

const IDENTIFY_ROUTE = {
    OTP_VIEW: 'OTP_VIEW',
    SELECT_PROVINCE: 'SELECT_PROVINCE',
    INVITE_CODE: 'INVITE_CODE',
    TERMS: 'TERMS',
};

const TUTORIAL_ROUTE = {
    ROOT: 'TUTORIAL',
    INTRO_APP: 'INTRO_APP',
};

const WEBVIEW_ROUTE = {
    WEBVIEW: 'WEBVIEW',
};

export {
    APP_ROUTE,
    TAB_NAVIGATION_ROOT,
    AUTHENTICATE_ROUTE,
    HOME_ROUTE,
    ASSESSMENT_ROUTE,
    IDENTIFY_ROUTE,
    TUTORIAL_ROUTE,
    ACCOUNT_ROUTE,
    HISTORY_ROUTE,
    WEBVIEW_ROUTE,
};
